### ISSUE TITLE
Verwijderen .idea en .docker

### ISSUE THREAD

**Issue by Tjoosten** [johanv/civiwwa#63]
In mijn opinie zijn dit omgevings bestanden. Nu is mijn vraag of deze verwijderd kunnen worden. Indien ja. Horen deze niet thuis in git in mijn opinie :)

**Comment by johanv** [comment]
`.idea` kan eventueel weg uit de repository. `.docker` niet, want daarin zit de definitie van de docker containers die gebuild moeten worden voor de omgeving gedefinieerd in `docker-compose.yml`.

Toegegeven, die docker-setup is niet optimaal geconfigureerd. Maar ik heb ze wel nodig om mijn lokale dev-omgeving aan de praat te krijgen.
